config/routes.rb
Rails.application.routes.draw do
  resources :trabalhos do
    get 'prazo_encerrado', on: :collection
    get 'aceite'
  end
  resources :minicursos do
    get 'prazo_encerrado', on: :collection
    get 'aceite'
  end
  resources :inscricoes do
    get 'encerradas', on: :collection
    get 'cancelar'
  end
  namespace :admin do
    resources :inscricoes
    resources :participantes do
      get 'credenciar'
      get 'aprovar_nota_empenho'
      get 'avaliar_isencao'
      get 'aprovar_pagamento'
      get 'confirmados', on: :collection
    end
    resources :organizadores
    resources :trabalhos do
      get 'avaliar'
      resources :avaliacoes, controller: 'avaliacoes_trabalhos'
    end
    resources :minicursos do
      get 'certificados'
      patch 'certificar'
      get 'participantes'
      resources :avaliacoes, controller: 'avaliacoes_minicursos'
    end
  end

  resources :sessions
  resources :participantes do
    get 'pagar'
  end

  resources :certificados

  root 'participantes#new'

  get 'cidades' => 'cidades#index', as: :cidades
  get 'login' => 'sessions#new', as: :login
  get 'logout' => 'sessions#destroy', as: :logout
  get 'admin' => 'admin#index', as: :admin
  get 'participacao' => 'participantes#participacao', as: :participacao
  get 'inscricoes_encerradas' => 'participantes#inscricoes_encerradas', as: :inscricoes_encerradas
  get 'conta' => 'usuarios#conta', as: :conta
  patch 'atualizar' => 'usuarios#atualizar', as: :atualizar_conta
  get 'recuperar_senha' => 'usuarios#recuperar_senha', as: :recuperar_senha
  post 'recuperacao_senha' => 'usuarios#recuperacao_senha', as: :recuperacao_senha
  get 'redefinir_senha' => 'usuarios#redefinir_senha', as: :redefinir_senha
  patch 'atualizar_senha' => 'usuarios#atualizar_senha', as: :atualizar_senha
  get "test_exception_notification" => "application#test_exception_notification"
  post 'pagamentos/:pagamento_id/notificar' => 'pagamentos#notificar', as: :notificar_pagamento
  get 'pagamentos/processando'
  get 'pagamentos/aprovado'
  get 'pagamentos/falhou'
  get 'usuarios/:usuario_id/personificar' => 'sessions#personificar', as: :personificar

end

app/models/trabalho.rb
class Trabalho < ApplicationRecord
  belongs_to :linha
  belongs_to :participante
  belongs_to :tipo_trabalho
  has_many :avaliacoes, class_name: 'AvaliacaoTrabalho', dependent: :destroy
  has_many :autores

  accepts_nested_attributes_for :autores, :reject_if => proc { |params| params['nome'].blank? }

  before_destroy :apagar_arquivo
  after_create :definir_avaliadores

  validates :titulo, :resumo, :linha_id, :tipo_trabalho_id, presence: true

  has_attached_file :arquivo, {
    path: "public/system/:class/:attachment/:id/:style/:filename",
    url: "system/:class/:attachment/:id/:style/:filename"
  }
  validates_attachment :arquivo, presence: true, content_type: { content_type: [ "application/msword", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" ] }

  def download
    if Rails.env.production?
      return "/semead/#{self.arquivo.url}"
    else
      return self.arquivo.url
    end
  end

  def minha_avaliacao(organizador)
    return self.avaliacoes.where(organizador_id: organizador.id).first
  end

  def apagar_arquivo
    self.arquivo.destroy
  end

  def definir_avaliadores
    2.times { self.atribuir_avaliador }
  end

  def avaliacoes_linha_atual
    avaliadores = self.avaliadores(self.linha)
    return self.avaliacoes.where("organizador_id in (#{avaliadores.map(&:id).join(',')})")
  end

  def avaliadores(linha = nil)
    avaliadores = Array.new
    self.avaliacoes.each do |avaliacao|
      if linha.present?
        if avaliacao.organizador.linhas.include?(linha)
          avaliadores << avaliacao.organizador
        end
      else
        avaliadores << avaliacao.organizador
      end
    end
    return avaliadores
  end

  def atribuir_avaliador
    avaliadores_candidatos = (self.linha.organizadores - self.avaliadores)
    if avaliadores_candidatos.empty?
      raise RuntimeError, 'Não há avaliadores suficientes para atribuir!'
    end

    avaliacoes = avaliadores_candidatos.first.avaliacoes_trabalhos.size
    avaliador = avaliadores_candidatos.first

    avaliadores_candidatos.each do |candidato|
      if candidato.avaliacoes_trabalhos.size < avaliacoes
        avaliacoes = candidato.avaliacoes_trabalhos.size
        avaliador = candidato
      end
    end

    AvaliacaoMailer.avaliacao_atribuida(avaliador, self).deliver_now
    self.avaliacoes << AvaliacaoTrabalho.new(trabalho: self, organizador: avaliador)
  end

  def situacao
    avaliacoes = self.avaliacoes_linha_atual
    avaliacoes.each do |avaliacao|
      if avaliacao.situacao == AvaliacaoTrabalho::SITUACOES[:pendente]
        return AvaliacaoTrabalho::SITUACOES[:pendente]
      end
    end

    aprovadas = 0
    reprovadas = 0
    outra_linha = 0
    avaliacoes.each do |avaliacao|
      aprovadas = aprovadas + 1 if avaliacao.situacao == AvaliacaoTrabalho::SITUACOES[:aprovado]
      reprovadas = reprovadas + 1 if avaliacao.situacao == AvaliacaoTrabalho::SITUACOES[:reprovado]
      outra_linha = outra_linha + 1 if avaliacao.situacao == AvaliacaoTrabalho::SITUACOES[:outra_linha]
    end

    if aprovadas > reprovadas and aprovadas > outra_linha
      return AvaliacaoTrabalho::SITUACOES[:aprovado]
    elsif reprovadas > aprovadas and reprovadas > outra_linha
      return AvaliacaoTrabalho::SITUACOES[:reprovado]
    elsif outra_linha > aprovadas and outra_linha > reprovadas
      return AvaliacaoTrabalho::SITUACOES[:outra_linha]
    else
      return AvaliacaoTrabalho::SITUACOES[:pendente]
    end
  end

  def self.aprovados
    self.all.select { |trabalho| trabalho.aprovado? }
  end

  def aprovado?
    return self.situacao == AvaliacaoTrabalho::SITUACOES[:aprovado]
  end

  def reprovado?
    return self.situacao == AvaliacaoTrabalho::SITUACOES[:reprovado]
  end

  def outra_linha?
    return self.situacao == AvaliacaoTrabalho::SITUACOES[:outra_linha]
  end
end

app/controllers/admin/trabalhos_controller.rb
class Admin::TrabalhosController < ApplicationController
  before_action :set_trabalho, only: [:show, :edit, :update, :destroy]

  def new
    if current_user.admin?
      @trabalho = Trabalho.new
      @trabalho.autores.build
    else
      redirect_to admin_trabalhos_path
    end
  end

  def index
    authorize! :index, Trabalho
    if current_user.tem_perfil?('administrador') or current_user.tem_perfil?('membro_comissao_central') or current_user.tem_perfil?('coordenador_comissao_cientifica') or current_user.tem_perfil?('secretario')
      @trabalhos = Trabalho.all
    elsif current_user.tem_perfil?('coordenador_linha_pesquisa') or current_user.tem_perfil?('membro_comissao_cientifica')
      @trabalhos = current_user.autenticavel.trabalhos
    end
  end

  def show
    authorize! :show, @trabalho
    if can? :index, AvaliacaoTrabalho
      @avaliacoes = @trabalho.avaliacoes
    end
    @avaliacao = @trabalho.minha_avaliacao(current_user.autenticavel)
  end

  def edit
    authorize! :update, @trabalho
  end

  def update
    authorize! :update, @trabalho
    respond_to do |format|
      if @trabalho.update(trabalho_params)
        format.html { redirect_to @trabalho, notice: 'Trabalho atualizado com sucesso!' }
        format.json { render :show, status: :ok, location: @trabalho }
      else
        format.html { render :edit }
        format.json { render json: @trabalho.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize! :destroy, @trabalho
    @trabalho.destroy
    respond_to do |format|
      format.html { redirect_to trabalhos_url, notice: 'Trabalho excluído com sucesso!' }
      format.json { head :no_content }
    end
  end

  def avaliar
    trabalho = Trabalho.find(params[:trabalho_id])
    authorize! :show, trabalho
    avaliacao = trabalho.minha_avaliacao(current_user.autenticavel)
    if avaliacao.present?
      redirect_to edit_admin_trabalho_avaliacao_path(trabalho, avaliacao)
    else
      redirect_to admin_trabalhos_path, alert: 'Você não é avaliador desse trabalho!'
    end
  end

  private

  def set_trabalho
    @trabalho = Trabalho.find(params[:id])
  end
end

app/controllers/trabalhos_controller.rb
class TrabalhosController < ApplicationController
  before_action :set_trabalho, only: [:show, :edit, :update, :destroy]
  before_action :set_participante, only: [ :create ]
  before_action :auth_required

  # GET /trabalhos
  # GET /trabalhos.json
  def index
    authorize! :index, Trabalho
    @trabalhos = current_user.autenticavel.trabalhos
  end

  # GET /trabalhos/1
  # GET /trabalhos/1.json
  def show
    authorize! :show, @trabalho
  end

  # GET /trabalhos/new
  def new
    if Config.instance.permitir_submissao_trabalhos?
      @trabalho = Trabalho.new
      @trabalho.participante = current_user.autenticavel
      @trabalho.autores.build(nome: current_user.autenticavel.nome)
      authorize! :create, @trabalho
    else
      redirect_to prazo_encerrado_trabalhos_path
    end

  end

  # GET /trabalhos/1/edit
  def edit
    authorize! :update, @trabalho
  end

  # POST /trabalhos
  # POST /trabalhos.json
  def create
    @trabalho = Trabalho.new(trabalho_params)
    authorize! :create, Trabalho

    respond_to do |format|
      if @trabalho.save
        ParticipanteMailer.trabalho_submetido(@trabalho.participante, @trabalho).deliver_now
        format.html { redirect_to trabalhos_path, notice: 'Trabalho enviado com sucesso!' }
        format.json { render :show, status: :created, location: @trabalho }
      else
        format.html { render :new }
        format.json { render json: @trabalho.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trabalhos/1
  # PATCH/PUT /trabalhos/1.json
  def update
    authorize! :update, @trabalho
    respond_to do |format|
      if @trabalho.update(trabalho_params)
        format.html { redirect_to @trabalho, notice: 'Trabalho atualizado com sucesso!' }
        format.json { render :show, status: :ok, location: @trabalho }
      else
        format.html { render :edit }
        format.json { render json: @trabalho.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trabalhos/1
  # DELETE /trabalhos/1.json
  def destroy
    authorize! :destroy, @trabalho
    @trabalho.destroy
    respond_to do |format|
      format.html { redirect_to trabalhos_url, notice: 'Trabalho excluído com sucesso!' }
      format.json { head :no_content }
    end
  end

  def prazo_encerrado
  end

  def aceite
    @trabalho = Trabalho.find(params[:trabalho_id])
    authorize! :aceite, @trabalho
    if @trabalho.aprovado?
      respond_to do |format|
        format.pdf do
          render pdf: 'aceite',
                 layout: 'aceite',
                 orientation: 'Portrait',
                 page_size: 'A4',
                 show_as_html: params.key?('debug')
        end
      end
    else
      redirect_to trabalhos_path, alert: 'Trabalho com avaliação pendente ou não aprovado!'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trabalho
      @trabalho = Trabalho.includes(:linha, :participante, :tipo_trabalho, :avaliacoes, :autores).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trabalho_params
      params.require(:trabalho).permit(:titulo, :resumo, :linha_id, :participante_id, :tipo_trabalho_id, :arquivo, autores_attributes: [ :nome ])
    end

    def set_participante
      if current_user.participante?
        params[:trabalho][:participante_id] = current_user.autenticavel.id
      end
    end
end

app/helpers/admin/trabalhos_helper.rb
module Admin::TrabalhosHelper
end

app/helpers/trabalhos_helper.rb
module TrabalhosHelper

  def situacao(situacao)
    if situacao == AvaliacaoTrabalho::SITUACOES[:aprovado]
      return "<span class='label label-success'>Aprovado</span>"
    elsif situacao == AvaliacaoTrabalho::SITUACOES[:reprovado]
      return "<span class='label label-danger'>Reprovado</span>"
    elsif situacao == AvaliacaoTrabalho::SITUACOES[:outra_linha]
      return "<span class='label label-warning'>Outra linha</span>"
    else
      return "<span class='label label-default'>Pendente</span>"
    end
  end

end

app/views/admin/trabalhos/_table.html.erb
<table id="datatable" class="table table-bordered table-hover">
  <thead>
    <tr>
      <th width="40%">Titulo</th>
      <th width="10%">Linha de pesquisa</th>
      <th width="10%">Tipo de trabalho</th>
      <th width="10%">Sua Avaliação</th>
      <th width="10%">Avaliação Geral</th>
      <th width="20%">Opções</th>
    </tr>
  </thead>
  <tbody>
    <% trabalhos.each do |trabalho| %>
      <tr>
        <td><%= trabalho.titulo %></td>
        <td><%= trabalho.linha.nome %></td>
        <td><%= trabalho.tipo_trabalho.nome %></td>
        <td>
          <% if trabalho.minha_avaliacao(current_user.autenticavel).present? %>
            <%= situacao(trabalho.minha_avaliacao(current_user.autenticavel).situacao).html_safe %>
          <% else %>
            -
          <% end %>
        </td>
        <td><%= situacao(trabalho.situacao).html_safe %></td>
        <td>
          <div class="btn-group">
            <% if can? :show, trabalho %>
              <%= link_to fa_icon('download'), trabalho.download, title: 'Download', class: 'btn btn-primary btn-sm' %>
            <% end %>
            <% if trabalho.minha_avaliacao(current_user.autenticavel).present? %>
              <%= link_to fa_icon('gavel'), admin_trabalho_avaliar_path(trabalho), title: 'Avaliar', class: 'btn btn-primary btn-sm' %>
            <% end %>
            <% if can? :show, trabalho %>
              <%= link_to fa_icon('eye'), admin_trabalho_path(trabalho), title: 'Detalhar', class: 'btn btn-primary btn-sm' %>
            <% end %>
            <% if can? :update, trabalho %>
              <%= link_to fa_icon('edit'), edit_admin_trabalho_path(trabalho), title: 'Editar', class: 'btn btn-primary btn-sm' %>
            <% end %>
            <% if can? :delete, trabalho %>
              <%= link_to fa_icon('trash'), admin_trabalho_path(trabalho), title: 'Excluir', class: "btn btn-primary btn-sm", method: :delete, data: { confirm: 'Tem certeza que deseja excluir esse trabalho?' } %>
            <% end %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/trabalhos/edit.html.erb
<div class="row">
  <div class="col-md-6">
    <h1><%= fa_icon 'edit' %> Editar Trabalho</h1>
  </div>
  <div class="col-md-6">
    <div class="btn-group pull-right">
      <% if can? :show, @trabalho %>
        <%= link_to fa_icon('download') + " Download", @trabalho.download, class: "btn btn-primary" %>
        <%= link_to fa_icon('eye') + " Detalhar", admin_trabalho_path(@trabalho), class: "btn btn-primary" %>
      <% end %>
      <% if can? :delete, @trabalho %>
        <%= link_to fa_icon('trash') + " Excluir", admin_trabalho_path(@trabalho), class: "btn btn-primary", method: :delete, data: { confirm: 'Tem certeza que deseja excluir esse trabalho?' } %>
      <% end %>
      <% if can? :index, Trabalho %>
        <%= link_to fa_icon('undo') + " Voltar", admin_trabalhos_path, class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

<%= render partial: 'trabalhos/form' %>

app/views/admin/trabalhos/index.html.erb
<% content_for :footer do %>
  <%= render partial: "layouts/datatables" %>
<% end %>

<div class="row">
  <div class="col-md-6">
    <h1><%= fa_icon 'file-text-o' %> Trabalhos</h1>
  </div>
  <div class="col-md-6">
    <div class="btn-group pull-right">
      <% if current_user.admin? %>
        <a href="<%= new_admin_trabalho_path %>" class="btn btn-primary"><%= fa_icon 'upload' %> Enviar Trabalho</a>
      <% end %>
    </div>
  </div>
</div>

<% if @trabalhos.empty? %>
  <p>Nenhum trabalho a ser avaliado por você até o momento.</p>
<% else %>
  <%= render partial: 'table', locals: { trabalhos: @trabalhos } %>
<% end %>

app/views/admin/trabalhos/new.html.erb
<div class="row">
  <div class="col-md-6">
    <h1><%= fa_icon 'upload' %> Enviar Trabalho</h1>
  </div>
</div>

<%= render "trabalhos/form" %>

app/views/admin/trabalhos/show.html.erb
<div class="row">
  <div class="col-md-6">
    <h1><%= fa_icon 'eye' %> Detalhar Trabalho</h1>
  </div>
  <div class="col-md-6">
    <div class="btn-group pull-right">
      <% if can? :show, @trabalho %>
        <%= link_to fa_icon('download') + " Download", @trabalho.download, class: "btn btn-primary" %>
      <% end %>
      <% if @avaliacao.present? and can? :edit, @avaliacao %>
        <%= link_to fa_icon('gavel') + " Avaliar", admin_trabalho_avaliar_path(@trabalho), class: "btn btn-primary" %>
      <% end %>
      <% if can? :update, @trabalho %>
        <%= link_to fa_icon('edit') + " Editar", edit_admin_trabalho_path(@trabalho), class: "btn btn-primary" %>
      <% end %>
      <% if can? :delete, @trabalho %>
        <%= link_to fa_icon('trash') + " Excluir", admin_trabalho_path(@trabalho), class: "btn btn-primary", method: :delete, data: { confirm: 'Tem certeza que deseja excluir esse trabalho?' } %>
      <% end %>
      <% if can? :index, Trabalho %>
        <%= link_to fa_icon('undo') + " Voltar", admin_trabalhos_path, class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

<h3><%= @trabalho.titulo %></h3>

<p><strong>Resumo</strong></p>

<p><%= @trabalho.resumo %></p>

<% if can? :ver_autores, @trabalho %>
  <p>
    <strong>Autor(es):</strong><br>
    <ul>
      <% if @trabalho.autores.empty? %>
        <li><%= link_to @trabalho.participante.nome, admin_participante_path(@trabalho.participante) %></li>
      <% else %>
        <% @trabalho.autores.each do |autor| %>
          <% if autor.nome.downcase == @trabalho.participante.nome.downcase %>
            <li><%= link_to @trabalho.participante.nome, admin_participante_path(@trabalho.participante) %></li>
          <% else %>
            <li><%= autor.nome %></li>
          <% end %>
        <% end %>
      <% end %>
    </ul>
  </p>
<% end %>

<p>
  <strong>Linha de pesquisa:</strong>
  <%= @trabalho.linha.nome %>
</p>

<p>
  <strong>Tipo de trabalho:</strong>
  <%= @trabalho.tipo_trabalho.nome %>
</p>

<p>
  <strong>Avaliação:</strong>
  <%= situacao(@trabalho.situacao).html_safe %>
</p>

<% if can? :index, AvaliacaoTrabalho %>
  <h2><%= fa_icon 'gavel' %> Avaliações</h2>
  <table class="table table-bordered table-hover">
    <thead>
      <th>Avaliador</th>
      <th>Avaliação</th>
      <th>Opções</th>
    </thead>
    <tbody>
      <% @avaliacoes.each do |avaliacao| %>
        <tr>
          <td><%= avaliacao.organizador.nome %></td>
          <td><%= situacao(avaliacao.situacao).html_safe %></td>
          <td><%= link_to fa_icon('eye'), admin_trabalho_avaliacao_path(avaliacao.trabalho, avaliacao), class: "btn btn-primary btn-sm" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>