config/routes.rb
Rails.application.routes.draw do
  resources :trabalhos do
    get 'prazo_encerrado', on: :collection
    get 'aceite'
  end
  resources :minicursos do
    get 'prazo_encerrado', on: :collection
    get 'aceite'
  end
  resources :inscricoes do
    get 'encerradas', on: :collection
    get 'cancelar'
  end
  namespace :admin do
    resources :inscricoes
    resources :participantes do
      get 'credenciar'
      get 'aprovar_nota_empenho'
      get 'avaliar_isencao'
      get 'aprovar_pagamento'
      get 'confirmados', on: :collection
    end
    resources :organizadores
    resources :trabalhos do
      get 'avaliar'
      resources :avaliacoes, controller: 'avaliacoes_trabalhos'
    end
    resources :minicursos do
      get 'certificados'
      patch 'certificar'
      get 'participantes'
      resources :avaliacoes, controller: 'avaliacoes_minicursos'
    end
  end

  resources :sessions
  resources :participantes do
    get 'pagar'
  end

  resources :certificados

  root 'participantes#new'

  get 'cidades' => 'cidades#index', as: :cidades
  get 'login' => 'sessions#new', as: :login
  get 'logout' => 'sessions#destroy', as: :logout
  get 'admin' => 'admin#index', as: :admin
  get 'participacao' => 'participantes#participacao', as: :participacao
  get 'inscricoes_encerradas' => 'participantes#inscricoes_encerradas', as: :inscricoes_encerradas
  get 'conta' => 'usuarios#conta', as: :conta
  patch 'atualizar' => 'usuarios#atualizar', as: :atualizar_conta
  get 'recuperar_senha' => 'usuarios#recuperar_senha', as: :recuperar_senha
  post 'recuperacao_senha' => 'usuarios#recuperacao_senha', as: :recuperacao_senha
  get 'redefinir_senha' => 'usuarios#redefinir_senha', as: :redefinir_senha
  patch 'atualizar_senha' => 'usuarios#atualizar_senha', as: :atualizar_senha
  get "test_exception_notification" => "application#test_exception_notification"
  post 'pagamentos/:pagamento_id/notificar' => 'pagamentos#notificar', as: :notificar_pagamento
  get 'pagamentos/processando'
  get 'pagamentos/aprovado'
  get 'pagamentos/falhou'
  get 'usuarios/:usuario_id/personificar' => 'sessions#personificar', as: :personificar

end

app/models/participante.rb
# encoding: utf-8

class Participante < ApplicationRecord
  include Selectable
  include GoogleDriveAPI

  belongs_to :tipo_participante
  belongs_to :cidade
  belongs_to :pais
  has_one :usuario, as: :autenticavel, dependent: :destroy
  has_many :trabalhos, dependent: :destroy
  has_many :pagamentos, dependent: :destroy
  has_many :minicursos_propostos, dependent: :destroy, class_name: 'Minicurso'
  has_many :inscricoes
  has_many :minicursos, through: :inscricoes

  has_attached_file :nota_empenho, {
    path: "public/system/:class/:attachment/:id/:style/:filename",
    url: "system/:class/:attachment/:id/:style/:filename"
  }

  validates :pais_id, :documento, :tipo_participante_id, :instituicao, presence: true
  validates :cidade_id, presence: true, if: :brasileiro?
  validates :documento, cpf: true, if: :brasileiro?
  validates :documento, uniqueness: true, on: :create
  validates :necessidades_especiais, presence: true, if: :possui_necessidades_especiais?
  validates_attachment :nota_empenho, presence: true, content_type: { content_type: "application/pdf" }, if: :pagamento_por_empenho?
  validates :motivo_isencao, presence: true, if: :isento?

  accepts_nested_attributes_for :usuario

  before_create :atribuir_perfil
  after_create :isencao_automatica

  ISENCAO = {
    :rejeitado => 0,
    :solicitado => 1,
    :aprovado => 2
  }

  def download_nota_empenho
    if Rails.env.production?
      return "/semead/#{self.nota_empenho.url}"
    else
      return "/#{self.nota_empenho.url}"
    end
  end

  def possui_necessidades_especiais?
    self.possui_necessidades_especiais.present?
  end

  def email
    self.usuario.email
  end

  def nome
    self.usuario.nome
  end

  def brasileiro?
    self.pais.brasil?
  end

  def atribuir_perfil
    self.usuario.perfil = Perfil.find_by_slug('participante')
  end

  def tipo?(tipo)
    return self.tipo_participante.slug == tipo
  end

  def pagamento_por_empenho?
    return self.pagamento_por_empenho
  end

  def aprovar_nota_empenho
    self.update_attribute(:pago, true)
    ParticipanteMailer.nota_empenho_aprovada(self).deliver_now
  end

  def pago?
    return self.pago
  end

  def tipo_documento
    if brasileiro?
      "CPF"
    else
      "passaporte"
    end
  end

  def isento?
    self.isento == ISENCAO[:aprovado]
  end

  def avaliar_isencao(avaliacao)
    self.update_attribute(:isento, avaliacao)
    if self.isencao_aprovada?
      ParticipanteMailer.isencao_aprovada(self).deliver_now
    else
      ParticipanteMailer.isencao_rejeitada(self).deliver_now
    end
  end

  def isencao_automatica
    if Isento.verificar(self.documento)
      self.avaliar_isencao(ISENCAO[:aprovado])
    end
  end

  def credenciar
    self.update_attribute(:credenciado, true)
  end

  def solicitou_isencao?
    self.isento == ISENCAO[:solicitado]
  end

  def isencao_aprovada?
    self.isento == ISENCAO[:aprovado]
  end

  def confirmado?
    self.pago? or self.isento?
  end

  def credenciado?
    self.credenciado
  end

  def respondeu_questionario?
    if self.respondeu_questionario
      return true
    else
      if questionario_respondido_por?(self.documento)
        self.update_attribute(:respondeu_questionario, true)
        return true
      end
      return false
    end
  end

  def self.select2(params)
    participantes = Array.new
    self.joins(:usuario).where("nome LIKE '%#{params}%'").each do |participante|
      participantes << { id: participante.id, nome: participante.nome }
    end
    return participantes
  end

  def self.confirmados
    self.joins(:usuario).where("pago = true OR isento = 2")
  end

  def self.credenciados
    self.joins(:usuario).where("credenciado = true")
  end

  def self.isentos
    self.joins(:usuario).where(isento: ISENCAO[:aprovado])
  end

  def self.pagantes
    self.joins(:usuario).where(pago: true)
  end
end

app/controllers/admin/participantes_controller.rb
class Admin::ParticipantesController < ApplicationController
  before_action :set_participante, only: [:show, :edit, :update, :destroy]

  def show
    authorize! :show, @participante
  end

  def edit
    authorize! :update, @participante
  end

  def update
    authorize! :update, @participante
    @participante.assign_attributes(participante_params)
    if @participante.save(validate: false)
      redirect_to admin_participante_path(@participante), notice: 'Participante atualizado com sucesso!'
    else
      render :edit, alert: 'Erro ao atualizar participante!'
    end
  end

  def aprovar_nota_empenho
    authorize! :aprovar_nota_empenho, Participante
    @participante = Participante.find(params[:participante_id])
    @participante.aprovar_nota_empenho
    redirect_to admin_participante_path(@participante), notice: 'Pagamento por nota de empenho aprovada!'
  end

  def aprovar_pagamento
    authorize! :aprovar_pagamento, Participante
    @participante = Participante.find(params[:participante_id])
    @participante.update_attribute(:pago, true)
    redirect_to admin_participante_path(@participante), notice: 'Pagamento aprovado com sucesso!'
  end

  def avaliar_isencao
    authorize! :avaliar_isencao, Participante
    @participante = Participante.find(params[:participante_id])
    @participante.avaliar_isencao(params[:avaliacao])
    redirect_to admin_participante_path(@participante), notice: 'Avaliação da isenção da taxa de inscrição realizada!'
  end

  def credenciar
    participante = Participante.find(params[:participante_id])
    authorize! :credenciar, participante
    if participante.confirmado?
      participante.credenciar
      redirect_to admin_participantes_path, notice: "#{participante.nome} credenciado com sucesso!"
    else
      redirect_to admin_participantes_path, error: "Não é possível credenciar um participante não-confirmado!"
    end
  end

  def new
    @participante = Participante.new
    @participante.usuario = Usuario.new
    authorize! :create, @participante
  end

  def index
    authorize! :index, Participante

    if params[:nome].nil?
      @participantes = Participante.includes(:cidade, :usuario).all
    else
      @participantes = Participante.joins(:usuario).includes(:cidade, :usuario).where("usuarios.nome LIKE \"%#{params[:nome]}%\"")
    end

    respond_to do |format|
      format.html
      format.json { render json: @participantes, include: :usuario }
      format.csv
    end
  end

  def confirmados
    authorize! :index, Participante
    @participantes = Participante.confirmados

    respond_to do |format|
      format.csv
    end
  end

  private

  def set_participante
    @participante = Participante.includes(:trabalhos, :pagamentos).find(params[:id])
  end

  def participante_params
    params.require(:participante).permit(:documento, :tipo_participante_id, :cidade_id, :pais_id, :instituicao, :possui_necessidades_especiais, :necessidades_especiais, :pagamento_por_empenho, :nota_empenho, :isento, :motivo_isencao, usuario_attributes: [ :nome, :email, :password, :password_confirmation ])
  end
end

app/controllers/participantes_controller.rb
class ParticipantesController < ApplicationController
  before_action :auth_required, :only => [ :participacao ]
  before_action :fix_isencao, :only => [ :create ]

  def participacao
    @participante = current_user.autenticavel
    authorize! :show, @participante
  end

  def pagar
    participante = Participante.find(params[:participante_id])
    pagamento = nil
    participante.pagamentos.each do |pgto|
      if Date.today <= pgto.prazo
        pagamento = pgto
        break
      end
    end
    if pagamento.nil? or Config.instance.dev?
      pagamento = Pagamento.gerar(participante)
    end

    if participante.pago?
      redirect_to participacao_path
    else
      redirect_to pagamento.mp_init_point
    end
  end

  def new
    if Config.instance.inscricoes_abertas?
      @participante = Participante.new
      @participante.usuario = Usuario.new
      render 'new', layout: 'publico'
    else
      redirect_to inscricoes_encerradas_path
    end
  end

  def create
    @participante = Participante.new(participante_params)
    respond_to do |format|
      if @participante.save
        session[:usuario_id] = @participante.usuario.id
        ParticipanteMailer.inscricao_realizada(@participante).deliver_now
        format.html { redirect_to participacao_path, notice: 'Inscrição realizada com sucesso!' }
        format.json { render :show, status: :created, location: @participante }
      else
        format.html { render :new }
        format.json { render json: @participante.errors, status: :unprocessable_entity }
      end
    end
  end

  def inscricoes_encerradas
  end

  private

    def fix_isencao
      if params[:participante][:isento] == "0"
        params[:participante][:isento] = nil
      else
        params[:participante][:isento] = 1
      end
    end

    def participante_params
      params.require(:participante).permit(:documento, :tipo_participante_id, :cidade_id, :pais_id, :instituicao, :possui_necessidades_especiais, :necessidades_especiais, :pagamento_por_empenho, :nota_empenho, :isento, :motivo_isencao, usuario_attributes: [ :nome, :email, :password, :password_confirmation ])
    end
end

app/helpers/admin/participantes_helper.rb
module Admin::ParticipantesHelper
end

app/helpers/participantes_helper.rb
module ParticipantesHelper

  def icons_listagem_participante(participante)
    html = ""
    if participante.possui_necessidades_especiais?
      html += fa_icon('wheelchair', title: 'Possui necessidades especiais')
      html += "&nbsp".html_safe
    end
    if participante.pagamento_por_empenho?
      html += fa_icon('file-text-o', title: 'Pagamento da taxa de inscrição por empenho')
      html += "&nbsp".html_safe
    elsif participante.isento? or participante.solicitou_isencao? or participante.isencao_aprovada?
      html += fa_icon('credit-card', classes: 'fa-disabled', title: 'Solicitou isenção/isento')
      html += "&nbsp".html_safe
    else
      html += fa_icon('credit-card', title: 'Pagamento da taxa de inscrição tradicional')
      html += "&nbsp".html_safe
    end
    if participante.confirmado?
      html += fa_icon('thumbs-up', title: 'Confirmado')
      html += "&nbsp".html_safe
    else
      html += fa_icon('thumbs-up', classes: 'fa-disabled', title: 'Não confirmado')
      html += "&nbsp".html_safe
    end
    if participante.credenciado?
      html += fa_icon('address-card-o', title: 'Credenciado')
      html += "&nbsp".html_safe
    end
    return html
  end

  def select2_default_option(participante)
    if participante.cidade.present?
      [ [ participante.cidade.nome_sigla, participante.cidade.id ] ]
    else
      cidade = Cidade.includes(:estado).where("cidades.nome = 'Natal'").first
      [ [ cidade.nome_sigla, cidade.id ] ]
    end
  end

  def isencao_options
    [ [ 'Organizador' ], [ 'Aluno do Campus EaD' ], [ 'Tutor(a) do Campus EaD' ] ]
  end

  def situacao_inscricao(participante)
    if participante.pago?
      return "<span class='label label-primary'>Pagamento confirmado</span>"
    elsif participante.pagamento_por_empenho?
      return "<span class='label label-warning'>Verificação da nota de empenho</span>"
    elsif participante.isento != nil
      if participante.isento == Participante::ISENCAO[:rejeitado]
        return "<span class='label label-danger'>Isenção rejeitada</span>"
      elsif participante.isento == Participante::ISENCAO[:solicitado]
        return "<span class='label label-warning'>Verificando isenção</span>"
      elsif participante.isento == Participante::ISENCAO[:aprovado]
        return "<span class='label label-primary'>Isenção aprovada</span>"
      end
    else
      return "<span class='label label-danger'>Pagamento pendente</span>"
    end
  end

end

app/views/admin/participantes/_inscricoes.html.erb
<% if inscricoes.empty? %>
  <p>Nenhuma inscrição realizada para minicurso até o momento.</p>
<% else %>
  <table class="table table-bordered table-hover">
    <thead>
      <th>Minicurso</th>
      <th>Emitir certificado?</th>
      <th>Opções</th>
    </thead>
    <tbody>
      <% inscricoes.each do |inscricao| %>
        <tr>
          <td><%= link_to inscricao.minicurso.titulo, admin_minicurso_path(inscricao.minicurso) %></td>
          <td><%= emitir_certificado?(inscricao) %></td>
          <td>
            <div class="btn-group">
              <%= link_to fa_icon('trash'), admin_inscricao_path(inscricao), method: :delete, class: "btn btn-primary btn-sm", data: { confirm: 'Tem certeza que deseja excluir essa inscrição?' } %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/admin/participantes/_table.html.erb
<table id="datatable" class="table table-bordered table-hover">
  <thead>
    <th>Nome</th>
    <th>CPF/Passaporte</th>
    <th>País/Cidade</th>
    <th>Observações</th>
    <th>Opções</th>
  </thead>
  <tbody>
    <% participantes.each do |participante| %>
      <tr>
        <td><%= participante.nome %></td>
        <td><%= participante.documento %></td>
        <td>
          <% if participante.pais.brasil? %>
            <%= participante.cidade.nome_sigla %>
          <% else %>
            <%= participante.pais.nome %>
          <% end %>
        </td>
        <td>
          <%= icons_listagem_participante(participante).html_safe %>
        </td>
        <td>
          <div class="btn-group">
            <% if can?(:personificar, participante.usuario) %>
              <%= link_to fa_icon('user-secret'), personificar_path(usuario_id: participante.usuario.id), class: "btn btn-primary btn-sm" %>
            <% end %>
            <% if can?(:credenciar, participante) and participante.confirmado? %>
              <% unless participante.credenciado? %>
                <%= link_to fa_icon('address-card-o'), admin_participante_credenciar_path(participante), title: 'Credenciar', class: "btn btn-primary btn-sm", data: { confirm: "Tem certeza que deseja credenciar #{participante.nome}?" } %>
              <% end %>
            <% end %>
            <% if can? :show, participante %>
              <%= link_to fa_icon('eye'), admin_participante_path(participante), title: 'Detalhar', class: "btn btn-primary btn-sm" %>
            <% end %>
            <% if can? :update, participante %>
              <%= link_to fa_icon('edit'), edit_admin_participante_path(participante), title: 'Editar', class: "btn btn-primary btn-sm" %>
            <% end %>
            <% if can? :destroy, participante %>
              <%= link_to fa_icon('trash'), admin_participante_path(participante), title: 'Excluir', class: "btn btn-primary btn-sm", method: :delete, data: { confirm: 'Tem certeza que deseja excluir esse participante?' } %>
            <% end %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/participantes/_trabalhos.html.erb
<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Linha de pesquisa</th>
      <th>Tipo de trabalho</th>
      <th colspan="3">Opções</th>
    </tr>
  </thead>
  <tbody>
    <% @participante.trabalhos.each do |trabalho| %>
      <tr>
        <td><%= trabalho.titulo %></td>
        <td><%= trabalho.linha.nome %></td>
        <td><%= trabalho.tipo_trabalho.nome %></td>
        <td>
          <div class="btn-group">
            <% if can? :show, trabalho %>
              <%= link_to fa_icon('download'), trabalho.download, class: 'btn btn-primary btn-sm' %>
              <%= link_to fa_icon('eye'), trabalho, class: 'btn btn-primary btn-sm' %>
            <% end %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/participantes/confirmados.csv.erb
<% @participantes.each do |participante| %>
"<%= participante.nome.mb_chars.upcase.to_s %>";"<%= participante.instituicao.mb_chars.upcase.to_s %>"
<% end %>

app/views/admin/participantes/edit.html.erb
<div class="row">
  <div class="col-md-6">
    <h1><%= fa_icon 'edit' %> Editar Participante</h1>
  </div>
  <div class="col-md-6">
    <div class="btn-group pull-right">
      <% if can? :show, @participante %>
        <%= link_to fa_icon('eye') + " Detalhar", admin_participante_path(@participante), class: "btn btn-primary" %>
      <% end %>
      <% if can? :delete, @participante %>
        <%= link_to fa_icon('trash') + " Excluir", admin_participante_path(@participante), class: "btn btn-primary", method: :delete, data: { confirm: 'Tem certeza que deseja excluir esse participante?' } %>
      <% end %>
      <% if can? :index, Participante %>
        <%= link_to fa_icon('undo') + " Voltar", admin_participantes_path, class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

<%= content_for :head do %>
  <script type="text/javascript">
    $(document).ready(function() {
      if(!$("#participante_possui_necessidades_especiais").is(':checked')) {
        $("#participante_necessidades_especiais").parent().hide();
      }

      if(!$("#participante_pagamento_por_empenho").is(':checked')) {
        $("#participante_nota_empenho").parent().hide();
      }

      if(!$("#participante_isento").is(':checked')) {
        $("#participante_motivo_isencao").parent().hide();
      }

      $("#participante_cidade_id").select2({
        theme: "bootstrap",
        language: "pt-BR",
        ajax: {
          url: "<%= cidades_path %>",
          dataType: 'json',
          delay: 250,
          data: function(params) {
            return {
              q: params.term,
              page: params.page
            }
          },
          processResults: function (data) {
            return {
              results: $.map(data, function (item) {
                          return {
                            text: item.nome,
                            id: item.id
                          }
                        })
            };
          },
          cache: true
        },
        escapeMarkup: function (markup) { return markup; }, // let our custom formatter work
        minimumInputLength: 3
      });
    });

    function toggle(id) {
      $("#participante_"+id).parent().toggle('blind');
    }

    function verificar_pais() {
      pais_id = $("#participante_pais_id").val();
      if(pais_id != 33) {
        $("#participante_cidade_id").attr('disabled', 'disabled');
      } else {
        $("#participante_cidade_id").attr('disabled', false);
      }
    }
  </script>
<% end %>

<%= bootstrap_form_for(@participante, url: admin_participante_path(@participante)) do |participante| %>
  <p>Os campos marcados com * são obrigatórios.</p>
  <%= participante.fields_for :usuario do |usuario| %>
    <%= usuario.text_field :nome, label: 'Nome completo *' %>
    <%= usuario.email_field :email, label: 'E-mail *' %>
    <%= usuario.password_field :password, placeholder: 'Mínimo de 4 caracteres', label: 'Senha *' %>
    <%= usuario.password_field :password_confirmation, placeholder: 'Repita a senha', label: 'Confirmação de senha *' %>
  <% end %>
  <%= participante.select :pais_id, Pais.select, {selected: 33, label: 'País *'}, {onchange: 'verificar_pais()'} %>
  <%= participante.select :cidade_id, select2_default_option(@participante), label: 'Cidade' %>
  <%= participante.text_field :documento, label: 'CPF/Passaporte *', placeholder: 'Apenas números' %>
  <%= participante.select :tipo_participante_id, TipoParticipante.select, prompt: 'Selecione', label: 'Perfil *' %>
  <%= participante.text_field :instituicao, label: 'Instituição *' %>
  <%= participante.check_box :isento, label: 'Sou isento do pagamento da taxa de inscrição', onchange: "toggle('motivo_isencao')" %>
  <%= participante.select :motivo_isencao, isencao_options, label: 'Motivo da isenção', prompt: 'Selecione' %>
  <%= participante.check_box :pagamento_por_empenho, label: 'Minha taxa de inscrição será paga por nota de empenho', onchange: "toggle('nota_empenho')" %>
  <%= participante.file_field :nota_empenho, label: 'Nota de empenho (pdf)' %>
  <%= participante.check_box :possui_necessidades_especiais, label: 'Você possui alguma necessidade específica?', onchange: "toggle('necessidades_especiais')" %>
  <%= participante.text_area :necessidades_especiais, label: 'Descreva a(s) sua(s) necessidade(s) específica(s)' %>
  <%= participante.submit 'Enviar', class: 'btn btn-primary' %>
<% end %>

app/views/admin/participantes/index.csv.erb
<% @participantes.each do |participante| %>
"<%= participante.nome.mb_chars.upcase.to_s %>";"<%= participante.documento %>";"<%= participante.email %>"
<% end %>

app/views/admin/participantes/index.html.erb
<%= content_for :head do %>
  <%= render "layouts/datatables" %>
<% end %>

<div class="row">
  <div class="col-md-6">
    <h1><%= fa_icon 'users' %> Participantes</h1>
  </div>
</div>

<% if @participantes.empty? %>
  <p>Nenhum participante encontrado.</p>
<% else %>
  <%= render partial: 'admin/participantes/table', locals: { participantes: @participantes } %>
  <p><%= @participantes.count %> participante(s) encontrado(s).</p>
<% end %>

app/views/admin/participantes/show.html.erb
<%= content_for :head do %>
  <script type="text/javascript">
    function aprovar_nota_empenho() {
      if(confirm("Tem certeza que deseja aprovar o pagamento por nota de empenho?")) {
        redirect("<%= admin_participante_aprovar_nota_empenho_path(@participante) %>");
      }
    }

    function avaliar_isencao(avaliacao) {
      if(confirm("Tem certeza que deseja avaliar a isenção da taxa de inscrição?")) {
        redirect("<%= admin_participante_avaliar_isencao_path(@participante) %>?avaliacao="+avaliacao);
      }
    }

    function aprovar_pagamento() {
      if(confirm("Tem certeza que deseja aprovar o pagamento?")) {
        redirect("<%= admin_participante_aprovar_pagamento_path(@participante) %>");
      }
    }
  </script>
<% end %>

<div class="row">
  <div class="col-md-6">
    <h1><%= fa_icon 'eye' %> Detalhar Participante</h1>
  </div>
  <div class="col-md-6">
    <div class="btn-group pull-right">
      <div class="btn-group">
        <% if can?(:aprovar_pagamento, @participante) or can?(:aprovar_nota_empenho, @participante) or can?(:aprovar_isencao, @participante) and not @participante.confirmado? %>
          <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Pagamento/Isenção <span class="caret"></span></button>
          <ul class="dropdown-menu">
            <% if can? :aprovar_pagamento, @participante and !(@participante.confirmado?) %>
              <li><%= link_to fa_icon('money') + " Aprovar pagamento", "javascript:void(0)", onclick: "aprovar_pagamento()" %></li>
            <% end %>
            <% if can? :aprovar_nota_empenho, @participante and !(@participante.confirmado?) %>
              <li><%= link_to fa_icon('file-text-o') + " Aprovar nota de empenho", "javascript:void(0)", onclick: "aprovar_nota_empenho()" %></li>
            <% end %>
            <% if can? :aprovar_isencao, @participante and !(@participante.confirmado?) %>
              <li><%= link_to fa_icon('thumbs-up') + " Aprovar isenção", "javascript:void(0)", onclick: "avaliar_isencao("+Participante::ISENCAO[:aprovado].to_s+")" %></li>
              <li><%= link_to fa_icon('thumbs-down') + " Rejeitar isenção", "javascript:void(0)", onclick: "avaliar_isencao("+Participante::ISENCAO[:rejeitado].to_s+")" %></li>
            <% end %>
          </ul>
        <% end %>
        <% if can? :update, @participante %>
          <%= link_to fa_icon('edit') + " Editar", edit_admin_participante_path(@participante), class: "btn btn-primary" %>
        <% end %>
        <% if can? :delete, @participante %>
          <%= link_to fa_icon('trash') + " Excluir", admin_participante_path(@participante), class: "btn btn-primary", method: :delete, data: { confirm: 'Tem certeza que deseja excluir esse participante?' } %>
        <% end %>
        <% if can? :index, Participante %>
          <%= link_to fa_icon('undo') + " Voltar", admin_participantes_path, class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= render partial: 'participantes/detalhes' %>

<hr>

<h2><%= fa_icon 'file-text-o' %> Trabalhos</h2>

<% if @participante.trabalhos.empty? %>
  <p>Nenhum trabalho submetido até o momento.</p>
<% else %>
  <%= render partial: 'trabalhos' %>
<% end %>

<hr>

<h2><%= fa_icon 'graduation-cap' %> Minicursos</h2>

<%= render partial: 'admin/minicursos/table', locals: { minicursos: @participante.minicursos_propostos } %>

<hr>

<h2><%= fa_icon 'pencil' %> Inscrições</h2>

<%= render partial: 'inscricoes', locals: { inscricoes: @participante.inscricoes } %>

<hr>

<h2><%= fa_icon 'certificate' %> Certificados</h2>

<%= render partial: 'certificados/table', locals: { certificados: @participante.usuario.certificados } %>

<hr>

<% if can? :show, Pagamento %>
  <h2><%= fa_icon 'usd' %> Pagamentos</h2>
  <% if @participante.pagamentos.empty? %>
    <p>Nenhum pagamento realizado até o momento.</p>
  <% else %>
    <%= render partial: 'pagamentos' %>
  <% end %>
<% end %>