config/routes.rb
Rails.application.routes.draw do
  resources :trabalhos do
    get 'prazo_encerrado', on: :collection
    get 'aceite'
  end
  resources :minicursos do
    get 'prazo_encerrado', on: :collection
    get 'aceite'
  end
  resources :inscricoes do
    get 'encerradas', on: :collection
    get 'cancelar'
  end
  namespace :admin do
    resources :inscricoes
    resources :participantes do
      get 'credenciar'
      get 'aprovar_nota_empenho'
      get 'avaliar_isencao'
      get 'aprovar_pagamento'
      get 'confirmados', on: :collection
    end
    resources :organizadores
    resources :trabalhos do
      get 'avaliar'
      resources :avaliacoes, controller: 'avaliacoes_trabalhos'
    end
    resources :minicursos do
      get 'certificados'
      patch 'certificar'
      get 'participantes'
      resources :avaliacoes, controller: 'avaliacoes_minicursos'
    end
  end

  resources :sessions
  resources :participantes do
    get 'pagar'
  end

  resources :certificados

  root 'participantes#new'

  get 'cidades' => 'cidades#index', as: :cidades
  get 'login' => 'sessions#new', as: :login
  get 'logout' => 'sessions#destroy', as: :logout
  get 'admin' => 'admin#index', as: :admin
  get 'participacao' => 'participantes#participacao', as: :participacao
  get 'inscricoes_encerradas' => 'participantes#inscricoes_encerradas', as: :inscricoes_encerradas
  get 'conta' => 'usuarios#conta', as: :conta
  patch 'atualizar' => 'usuarios#atualizar', as: :atualizar_conta
  get 'recuperar_senha' => 'usuarios#recuperar_senha', as: :recuperar_senha
  post 'recuperacao_senha' => 'usuarios#recuperacao_senha', as: :recuperacao_senha
  get 'redefinir_senha' => 'usuarios#redefinir_senha', as: :redefinir_senha
  patch 'atualizar_senha' => 'usuarios#atualizar_senha', as: :atualizar_senha
  get "test_exception_notification" => "application#test_exception_notification"
  post 'pagamentos/:pagamento_id/notificar' => 'pagamentos#notificar', as: :notificar_pagamento
  get 'pagamentos/processando'
  get 'pagamentos/aprovado'
  get 'pagamentos/falhou'
  get 'usuarios/:usuario_id/personificar' => 'sessions#personificar', as: :personificar

end

app/models/minicurso.rb
class Minicurso < ApplicationRecord
  belongs_to :participante # Proponente/ministrante
  has_many :inscricoes
  has_many :participantes, through: :inscricoes

  validates :titulo, :justificativa, :objetivos, :metodologia, :programacao, :material, :referencias, presence: true, on: :create
  validates :titulo, :justificativa, :objetivos, :metodologia, :programacao, :material, :referencias, :vagas, :local, presence: true, on: :update
  validates :vagas, numericality: { only_integer: true }, on: :update

  before_create :definir_avaliacao

  AVALIACAO = {
    reprovado: -1,
    pendente: 0,
    aprovado: 1
  }

  def definir_avaliacao
    self.avaliacao = AVALIACAO[:pendente]
  end

  def self.aprovados
    self.where(avaliacao: AVALIACAO[:aprovado])
  end

  def self.com_vagas
    minicursos = Array.new
    Minicurso.aprovados.each do |minicurso|
      minicursos << minicurso if minicurso.tem_vagas?
    end
    return minicursos
  end

  def vagas_disponiveis
    self.vagas - self.participantes.size
  end

  def tem_vagas?
    self.vagas_disponiveis > 0
  end

  def aprovado?
    self.avaliacao == AVALIACAO[:aprovado]
  end

  def carga_horaria
    4
  end
end

app/controllers/admin/minicursos_controller.rb
class Admin::MinicursosController < ApplicationController
  before_action :set_minicurso, only: [:edit, :update, :destroy]

  def index
    authorize! :index, Minicurso
    @minicursos = Minicurso.all
  end

  def new
    authorize! :new, Minicurso
    @minicurso = Minicurso.new
  end

  def create
    @minicurso = Minicurso.new(minicurso_params)
    authorize! :new, @minicurso

    if @minicurso.save
      redirect_to admin_minicursos_path, notice: 'Minicurso cadastrado com sucesso!'
    else
      render :new
    end
  end

  def edit
    authorize! :edit, @minicurso
  end

  def update
    authorize! :update, @minicurso
    respond_to do |format|
      if @minicurso.update(minicurso_params)
        format.html { redirect_to admin_minicurso_path(@minicurso), notice: 'Minicurso atualizado com sucesso!' }
        format.json { render :show, status: :ok, location: @minicurso }
      else
        format.html { render :edit }
        format.json { render json: @minicurso.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @minicurso = Minicurso.includes(:inscricoes).find(params[:id])
    @inscricao = Inscricao.new(minicurso: @minicurso)
    authorize! :show, @minicurso
  end

  def certificados
    authorize! :certificar, Minicurso
    @minicurso = Minicurso.includes(:inscricoes).find(params[:minicurso_id])
  end

  def participantes
    @minicurso = Minicurso.includes(:inscricoes).find(params[:minicurso_id])
    authorize! :show, @minicurso
    respond_to do |format|
      format.csv
    end
  end

  def certificar
    authorize! :certificar, Minicurso
    @minicurso = Minicurso.includes(:inscricoes).find(params[:minicurso_id])
    @minicurso.inscricoes.each do |inscricao|
      inscricao.update_attribute(:certificado, params["#{inscricao.id}"].to_i)
    end
    redirect_to admin_minicurso_certificados_path(@minicurso), notice: 'Certificação realizada com sucesso!'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_minicurso
      @minicurso = Minicurso.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def minicurso_params
      params.require(:minicurso).permit(:titulo, :justificativa, :objetivos, :metodologia, :programacao, :material, :referencias, :participante_id, :vagas, :local, :avaliacao)
    end
end

app/controllers/minicursos_controller.rb
class MinicursosController < ApplicationController
  before_action :set_minicurso, only: [:show, :edit, :update, :destroy]
  before_action :set_participante, only: [ :create ]
  before_action :auth_required

  def index
    authorize! :index, Minicurso
    @minicursos = current_user.autenticavel.minicursos_propostos
  end

  def new
    if Config.instance.permitir_submissao_minicursos?
      authorize! :new, Minicurso
      @minicurso = Minicurso.new
    else
      redirect_to prazo_encerrado_minicursos_path
    end
  end

  def prazo_encerrado
  end

  def create
    authorize! :create, Minicurso
    @minicurso = Minicurso.new(minicurso_params)

    respond_to do |format|
      if @minicurso.save
        ParticipanteMailer.minicurso_proposto(@minicurso.participante, @minicurso).deliver_now
        format.html { redirect_to minicursos_path, notice: 'Minicurso proposto com sucesso!' }
      else
        format.html { render :new }
      end
    end
  end

  def aceite
    @minicurso = Minicurso.find(params[:minicurso_id])
    authorize! :aceite, @minicurso
    if @minicurso.aprovado?
      respond_to do |format|
        format.pdf do
          render pdf: 'aceite',
                 layout: 'aceite',
                 orientation: 'Portrait',
                 page_size: 'A4',
                 show_as_html: params.key?('debug')
        end
      end
    else
      redirect_to minicursos_path, alert: 'Minicurso com avaliação pendente ou não aprovado!'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_minicurso
      @minicurso = Minicurso.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def minicurso_params
      params.require(:minicurso).permit(:titulo, :justificativa, :objetivos, :metodologia, :programacao, :material, :referencias, :participante_id)
    end

    def set_participante
      params[:minicurso][:participante_id] = current_user.autenticavel.id
    end
end

app/helpers/admin/minicursos_helper.rb
module Admin::MinicursosHelper
end

app/helpers/minicursos_helper.rb
module MinicursosHelper

  def avaliacao_minicurso(avaliacao)
    if avaliacao == Minicurso::AVALIACAO[:aprovado]
      return "<span class='label label-success'>Aprovado</span>"
    elsif avaliacao == Minicurso::AVALIACAO[:reprovado]
      return "<span class='label label-danger'>Reprovado</span>"
    else
      return "<span class='label label-default'>Pendente</span>"
    end
  end

  def avaliacao_options
    [['Reprovado', -1], ['Pendente', 0], ['Aprovado', 1]]
  end

end

app/views/minicursos/_detalhes.html.erb
<p><strong>Avaliação:</strong> <%= avaliacao_minicurso(@minicurso.avaliacao).html_safe %></p>

<dl>
  <dt>Título</dt>
  <dd><%= @minicurso.titulo %></dd>
  <dt>Ministrante</dt>
  <dd><%= @minicurso.participante.nome %></dd>
  <dt>Justificativa</dt>
  <dd><%= @minicurso.justificativa %></dd>
  <dt>Objetivos</dt>
  <dd><%= @minicurso.objetivos %></dd>
  <dt>Metodologia</dt>
  <dd><%= @minicurso.metodologia %></dd>
  <dt>Programação</dt>
  <dd><%= @minicurso.programacao %></dd>
  <dt>Material necessário</dt>
  <dd><%= @minicurso.material %></dd>
  <dt>Referências</dt>
  <dd><%= @minicurso.referencias %></dd>
  <% if @minicurso.local.present? %>
    <dt>Local</dt>
    <dd><%= @minicurso.local %></dd>
  <% end %>
  <% if @minicurso.vagas.present? %>
    <dt>Vagas</dt>
    <dd><%= @minicurso.vagas %></dd>
  <% end %>
</dl>

app/views/minicursos/_form.html.erb
<%= bootstrap_form_for(@minicurso) do |f| %>
  <p>Todos os campos são obrigatórios.</p>
  <%= f.text_field :titulo, label: 'Título' %>
  <div class="row">
    <div class="col-md-6 col-sm-12">
      <%= f.text_area :justificativa, rows: 5 %>
      <%= f.text_area :objetivos, rows: 5 %>
      <%= f.text_area :metodologia, rows: 5 %>
    </div>
    <div class="col-md-6 col-sm-12">
      <%= f.text_area :programacao, rows: 5, label: 'Programação' %>
      <%= f.text_area :material, rows: 5, label: 'Material necessário' %>
      <%= f.text_area :referencias, rows: 5, label: 'Referências' %>
    </div>
  </div>
  <%= f.submit 'Enviar', class: 'btn btn-primary' %>
<% end %>

app/views/minicursos/aceite.pdf.erb
<p>Prezado(a) autor(a)</p>

<p>
  <strong><%= @minicurso.participante.nome %></strong>
</p>

<p class="justify">A Comissão Organizadora do III Seminário Internacional de Educação a Distância: Cenário Atual e Perspectivas da Educação a Distância tem a satisfação de comunicar que seu minicurso, intitulado <%= @minicurso.titulo.upcase %>, foi <strong>APROVADO</strong> pela Comissão Científica.
</p>

<p class="justify">O local e o horário da realização do seu minicurso serão divulgados, posteriormente, na página do evento.</p>

app/views/minicursos/edit.html.erb
<h1>Minicursos#edit</h1>
<p>Find me in app/views/minicursos/edit.html.erb</p>

app/views/minicursos/index.html.erb
<div class="row">
  <div class="col-md-6">
    <h1><%= fa_icon 'graduation-cap' %> Minicursos</h1>
  </div>
  <div class="col-md-6">
    <div class="btn-group pull-right">
      <% if Config.instance.permitir_submissao_minicursos? and can? :new, Minicurso %>
        <a href="<%= new_minicurso_path %>" class="btn btn-primary"><%= fa_icon 'graduation-cap' %> Propor Minicurso</a>
      <% end %>
    </div>
  </div>
</div>

<% if @minicursos.empty? %>
  <p>Você não propôs nenhum minicurso.</p>
<% else %>
  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th>Titulo</th>
        <th>Avaliação</th>
        <th>Opções</th>
      </tr>
    </thead>
    <tbody>
      <% @minicursos.each do |minicurso| %>
        <tr>
          <td><%= minicurso.titulo %></td>
          <td><%= avaliacao_minicurso(minicurso.avaliacao).html_safe %></td>
          <td>
            <div class="btn-group">
              <% if minicurso.aprovado? and can? :aceite, minicurso %>
                <%= link_to fa_icon('envelope'), minicurso_aceite_path(minicurso, format: :pdf), title: 'Carta de aceite', class: 'btn btn-primary btn-sm' %>
              <% end %>
              <% if can? :show, minicurso %>
                <%= link_to fa_icon('eye'), minicurso, title: 'Detalhar', class: 'btn btn-primary btn-sm' %>
              <% end %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/minicursos/new.html.erb
<div class="row">
  <div class="col-md-6">
    <h1><%= fa_icon 'graduation-cap' %> Propor Minicurso</h1>
  </div>
  <div class="col-md-6">
    <div class="btn-group pull-right">
      <a href="<%= minicursos_path %>" class="btn btn-primary"><%= fa_icon 'undo' %> Voltar</a>
    </div>
  </div>
</div>

<%= render 'form' %>

app/views/minicursos/prazo_encerrado.html.erb
<h1>Prazo encerrado!</h1>

<p>Infelizmente o prazo para submissão de minicursos para a III SEMEAD se encerrou em <%= data(Config.instance.data_termino_submissao_minicursos) %>.</p>

app/views/minicursos/show.html.erb
<div class="row">
  <div class="col-md-6">
    <h1><%= fa_icon 'graduation-cap' %> Minicurso</h1>
  </div>
  <div class="col-md-6">
    <div class="btn-group pull-right">
      <a href="<%= minicursos_path %>" class="btn btn-primary"><%= fa_icon 'undo' %> Voltar</a>
    </div>
  </div>
</div>

<%= render partial: 'detalhes' %>