config/routes.rb
Rails.application.routes.draw do
  resources :trabalhos do
    get 'prazo_encerrado', on: :collection
    get 'aceite'
  end
  resources :minicursos do
    get 'prazo_encerrado', on: :collection
    get 'aceite'
  end
  resources :inscricoes do
    get 'encerradas', on: :collection
    get 'cancelar'
  end
  namespace :admin do
    resources :inscricoes
    resources :participantes do
      get 'credenciar'
      get 'aprovar_nota_empenho'
      get 'avaliar_isencao'
      get 'aprovar_pagamento'
      get 'confirmados', on: :collection
    end
    resources :organizadores
    resources :trabalhos do
      get 'avaliar'
      resources :avaliacoes, controller: 'avaliacoes_trabalhos'
    end
    resources :minicursos do
      get 'certificados'
      patch 'certificar'
      get 'participantes'
      resources :avaliacoes, controller: 'avaliacoes_minicursos'
    end
  end

  resources :sessions
  resources :participantes do
    get 'pagar'
  end

  resources :certificados

  root 'participantes#new'

  get 'cidades' => 'cidades#index', as: :cidades
  get 'login' => 'sessions#new', as: :login
  get 'logout' => 'sessions#destroy', as: :logout
  get 'admin' => 'admin#index', as: :admin
  get 'participacao' => 'participantes#participacao', as: :participacao
  get 'inscricoes_encerradas' => 'participantes#inscricoes_encerradas', as: :inscricoes_encerradas
  get 'conta' => 'usuarios#conta', as: :conta
  patch 'atualizar' => 'usuarios#atualizar', as: :atualizar_conta
  get 'recuperar_senha' => 'usuarios#recuperar_senha', as: :recuperar_senha
  post 'recuperacao_senha' => 'usuarios#recuperacao_senha', as: :recuperacao_senha
  get 'redefinir_senha' => 'usuarios#redefinir_senha', as: :redefinir_senha
  patch 'atualizar_senha' => 'usuarios#atualizar_senha', as: :atualizar_senha
  get "test_exception_notification" => "application#test_exception_notification"
  post 'pagamentos/:pagamento_id/notificar' => 'pagamentos#notificar', as: :notificar_pagamento
  get 'pagamentos/processando'
  get 'pagamentos/aprovado'
  get 'pagamentos/falhou'
  get 'usuarios/:usuario_id/personificar' => 'sessions#personificar', as: :personificar

end

app/models/certificado.rb
class Certificado < ApplicationRecord
  belongs_to :usuario

  before_create :definir_texto, :processar_fragmentos

  INICIO = "Certificamos que "
  FINAL = " III Seminário Internacional de Educação a Distância, realizado no Campus de Educação a Distância do Instituto Federal de Educação, Ciência e Tecnologia do Rio Grande do Norte, entre os dias 10 e 12 de maio de 2017."

  def data
    I18n.l self.created_at, format: :long
  end

  private

  def definir_texto
    self.texto = INICIO + self.texto + FINAL
  end

  def processar_fragmentos
    self.texto.gsub!("[nome]", "<strong>#{self.usuario.nome}</strong>")
    self.texto.gsub!("[b]", "<strong>")
    self.texto.gsub!("[/b]", "</strong>")
  end

end

app/controllers/certificados_controller.rb
class CertificadosController < ApplicationController
  before_action :auth_required

  def index
    authorize! :index, Certificado
    @certificados = current_user.certificados
  end

  def new
    authorize! :new, Certificado
    @certificado = Certificado.new
  end

  def create
    authorize! :new, Certificado
    @certificado = Certificado.new(certificado_params)
    if @certificado.save
      redirect_to certificado_path(@certificado, format: :pdf)
    else
      render :new
    end
  end

  def show
    @certificado = Certificado.find(params[:id])
    authorize! :show, @certificado

    if @certificado.usuario.participante? and (not @certificado.usuario.autenticavel.respondeu_questionario?)
      redirect_to Config.instance.url_questionario_avaliacao
    else
      respond_to do |format|
        format.pdf do
          render pdf: 'certificado',
                 layout: 'certificado',
                 orientation: 'Landscape',
                 page_size: 'A4',
                 background: true,
                 lowquality: false,
                 grayscale: false,
                 no_background: false,
                 show_as_html: params.key?('debug'),
                 margin: {
                   top: 0, bottom: 0, left: 0, right: 0
                 }
        end
      end
    end
  end

  private

  def certificado_params
    params.require(:certificado).permit(:titulo, :usuario_id, :texto)
  end
end

app/helpers/certificados_helper.rb
module CertificadosHelper
end

app/views/certificados/_table.html.erb
<% if certificados.empty? %>
  <p>Nenhum certificado emitido até o momento.</p>
<% else %>
  <table class="table table-bordered table-hover">
    <thead>
      <th>Título</th>
      <th>Opções</th>
    </thead>
    <tbody>
      <% certificados.each do |certificado| %>
        <tr>
          <td><%= certificado.titulo %></td>
          <td>
            <div class="btn-group">
              <%= link_to fa_icon('eye'), certificado_path(certificado, format: :pdf), class: "btn btn-primary btn-sm" %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/certificados/index.html.erb
<div class="row">
  <div class="col-md-6">
    <h1><%= fa_icon 'certificate' %> Certificados</h1>
  </div>
  <div class="col-md-6">
    <div class="btn-group pull-right">
      <% if can? :new, Certificado %>
        <a href="<%= new_certificado_path %>" class="btn btn-primary"><%= fa_icon 'certificate' %> Novo Certificado</a>
      <% end %>
    </div>
  </div>
</div>

<% if current_user.participante? and (not current_user.autenticavel.respondeu_questionario?) %>
  <div class="alert alert-danger" role="alert">
    <strong>Atenção:</strong> Para emitir os certificados, primeiramente você deve responder ao <%= link_to "Questionário de Avaliação da III SEMEAD", Config.instance.url_questionario_avaliacao, target: '_blank' %>.
  </div>
<% else %>
  <%= render partial: 'table', locals: { certificados: @certificados } %>
<% end %>

app/views/certificados/new.html.erb
<%= content_for :head do %>
  <script type="text/javascript">
    $(function() {
      $("#certificado_usuario_id").select2({
        theme: "bootstrap"
      });
    });
  </script>
<% end %>

<div class="row">
  <div class="col-md-6">
    <h1><%= fa_icon 'certificate' %> Novo Certificado</h1>
  </div>
  <div class="col-md-6">
    <div class="btn-group pull-right">
      <a href="<%= certificados_path %>" class="btn btn-primary"><%= fa_icon 'undo' %> Voltar</a>
    </div>
  </div>
</div>

<%= bootstrap_form_for(@certificado) do |f| %>
  <%= f.text_field :titulo, label: 'Título' %>
  <%= f.select :usuario_id, Usuario.select, prompt: 'Selecione', label: 'Usuário' %>
  <div class="row">
    <div class="col-md-8">
      <p>Certificamos que [...]</p>
      <%= f.text_area :texto, rows: 5, hide_label: true, placeholder: 'Digite aqui o corpo do certificado' %>
      <p>[...] III Seminário Internacional de Educação a Distância, realizado no Campus de Educação a Distância do Instituto Federal de Educação, Ciência e Tecnologia do Rio Grande do Norte, entre os dias 10 e 12 de maio de 2017.</p>
    </div>
    <div class="col-md-4">
      <p>Fragmentos disponíveis</p>
      <ul>
        <li><strong>[nome]</strong>: nome do usuário</li>
        <li><strong>[b]</strong>: início do texto em negrito</li>
        <li><strong>[/b]</strong>: fim do texto em negrito</li>
      </ul>
    </div>
  </div>
  <%= f.submit 'Enviar', class: 'btn btn-primary' %>
<% end %>

app/views/certificados/show.pdf.erb
<p>
  <%= @certificado.texto.html_safe %>
</p>

<p class="right-side">
  Natal, <%= @certificado.data %>
</p>